# Generated by Django 4.2.11 on 2026-05-27 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('hf', 'Hartree-Fock'), ('dft', 'DFT'), ('inputs', 'Input Cards'), ('runtime', 'Runtime'), ('physics', 'Physics')], default='physics', max_length=30)),
                ('summary', models.CharField(max_length=280)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=80)),
                ('seo_description', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theory_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeControlPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('theory', models.CharField(default='hf', max_length=30)),
                ('grid_spec', models.CharField(default='151 35.0', max_length=80)),
                ('orbpot', models.CharField(default='hf', max_length=80)),
                ('scf_iterations', models.PositiveIntegerField(default=1000)),
                ('scf_orbital', models.FloatField(default=1e-06)),
                ('scf_potential', models.FloatField(default=1e-06)),
                ('advanced_cards', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['theory', 'name'],
            },
        ),
    ]
