import React,{useEffect,useMemo,useState} from 'react';
import {useDispatch} from 'react-redux';
import {computationAPI} from '../api/client';
import {submitComputation} from '../store/computationSlice';

const defaults={title:'H HF Python X2DHF',description:'Structured Python science runtime input',theory:'hf',functional:'xc_lda_x',functionalCustom:'',molecular_system:'',moleculeMode:'atom',atomA:'H',atomB:'None',za:'1.0',zb:'0.0',r:'2.0',charge:'0',orbitals:'1 sigma + end',gridSpec:'151 35.0',orbpot:'hydrogen',lcao:'1.0 1 0 1.0 0.0 1 0 1.0',scfMacro:'1000',scfOrbital:'10',scfPotential:'12',scfExtra:'16',scfMix:'3',conv:'',multipol:'',advancedCards:'',properties:false};
const functionals=['xc_lda_x','xc_lda_x xc_lda_c_vwn','xc_gga_x_b88','xc_gga_x_b88 xc_gga_c_lyp','xc_gga_x_pbe xc_gga_c_pbe','xc_hyb_gga_xc_b3lyp','custom'];
const iterationPresets=[1000,10000,100000,1000000,5000000];
const moleculePresets=[['H2','diatomic','H','H','1.4'],['HeH+','diatomic','He','H','1.5'],['LiH','diatomic','Li','H','3.0'],['BeH','diatomic','Be','H','2.5'],['BH','diatomic','B','H','2.3'],['CH','diatomic','C','H','2.1'],['NH','diatomic','N','H','2.0'],['OH','diatomic','O','H','1.8'],['HF','diatomic','H','F','1.73'],['CO','diatomic','C','O','2.13'],['NO','diatomic','N','O','2.17'],['N2','diatomic','N','N','2.08'],['O2','diatomic','O','O','2.28'],['F2','diatomic','F','F','2.67'],['HCl','diatomic','H','Cl','2.41'],['NaCl','diatomic','Na','Cl','4.45'],['KCl','diatomic','K','Cl','5.0'],['LiF','diatomic','Li','F','2.96'],['CN','diatomic','C','N','2.2'],['FeO','diatomic','Fe','O','3.0']];
const elements=[['None',0,'No second centre'],['H',1,'Hydrogen'],['He',2,'Helium'],['Li',3,'Lithium'],['Be',4,'Beryllium'],['B',5,'Boron'],['C',6,'Carbon'],['N',7,'Nitrogen'],['O',8,'Oxygen'],['F',9,'Fluorine'],['Ne',10,'Neon'],['Na',11,'Sodium'],['Mg',12,'Magnesium'],['Al',13,'Aluminium'],['Si',14,'Silicon'],['P',15,'Phosphorus'],['S',16,'Sulfur'],['Cl',17,'Chlorine'],['Ar',18,'Argon'],['K',19,'Potassium'],['Ca',20,'Calcium'],['Sc',21,'Scandium'],['Ti',22,'Titanium'],['V',23,'Vanadium'],['Cr',24,'Chromium'],['Mn',25,'Manganese'],['Fe',26,'Iron'],['Co',27,'Cobalt'],['Ni',28,'Nickel'],['Cu',29,'Copper'],['Zn',30,'Zinc'],['Ga',31,'Gallium'],['Ge',32,'Germanium'],['As',33,'Arsenic'],['Se',34,'Selenium'],['Br',35,'Bromine'],['Kr',36,'Krypton'],['Rb',37,'Rubidium'],['Sr',38,'Strontium'],['Y',39,'Yttrium'],['Zr',40,'Zirconium'],['Nb',41,'Niobium'],['Mo',42,'Molybdenum'],['Tc',43,'Technetium'],['Ru',44,'Ruthenium'],['Rh',45,'Rhodium'],['Pd',46,'Palladium'],['Ag',47,'Silver'],['Cd',48,'Cadmium'],['In',49,'Indium'],['Sn',50,'Tin'],['Sb',51,'Antimony'],['Te',52,'Tellurium'],['I',53,'Iodine'],['Xe',54,'Xenon'],['Cs',55,'Caesium'],['Ba',56,'Barium'],['La',57,'Lanthanum'],['Ce',58,'Cerium'],['Pr',59,'Praseodymium'],['Nd',60,'Neodymium'],['Pm',61,'Promethium'],['Sm',62,'Samarium'],['Eu',63,'Europium'],['Gd',64,'Gadolinium'],['Tb',65,'Terbium'],['Dy',66,'Dysprosium'],['Ho',67,'Holmium'],['Er',68,'Erbium'],['Tm',69,'Thulium'],['Yb',70,'Ytterbium'],['Lu',71,'Lutetium'],['Hf',72,'Hafnium'],['Ta',73,'Tantalum'],['W',74,'Tungsten'],['Re',75,'Rhenium'],['Os',76,'Osmium'],['Ir',77,'Iridium'],['Pt',78,'Platinum'],['Au',79,'Gold'],['Hg',80,'Mercury'],['Tl',81,'Thallium'],['Pb',82,'Lead'],['Bi',83,'Bismuth'],['Po',84,'Polonium'],['At',85,'Astatine'],['Rn',86,'Radon'],['Fr',87,'Francium'],['Ra',88,'Radium'],['Ac',89,'Actinium'],['Th',90,'Thorium'],['Pa',91,'Protactinium'],['U',92,'Uranium'],['Np',93,'Neptunium'],['Pu',94,'Plutonium'],['Am',95,'Americium'],['Cm',96,'Curium'],['Bk',97,'Berkelium'],['Cf',98,'Californium'],['Es',99,'Einsteinium'],['Fm',100,'Fermium'],['Md',101,'Mendelevium'],['No',102,'Nobelium'],['Lr',103,'Lawrencium'],['Rf',104,'Rutherfordium'],['Db',105,'Dubnium'],['Sg',106,'Seaborgium'],['Bh',107,'Bohrium'],['Hs',108,'Hassium'],['Mt',109,'Meitnerium'],['Ds',110,'Darmstadtium'],['Rg',111,'Roentgenium'],['Cn',112,'Copernicium'],['Nh',113,'Nihonium'],['Fl',114,'Flerovium'],['Mc',115,'Moscovium'],['Lv',116,'Livermorium'],['Ts',117,'Tennessine'],['Og',118,'Oganesson']];
const elementMap=Object.fromEntries(elements.map(([symbol,z,name])=>[symbol,{symbol,z,name}]));
const help={title:'Human-readable run name used in dashboards and output history.',description:'Notes for remembering why this calculation was submitted.',theory:'Select the Python X2DHF method card.',functional:'Libxc-style DFT functional labels preserved in the Python DFT runtime.',functionalCustom:'Type any Libxc label combination, for example xc_gga_x_b88 xc_gga_c_lyp.',moleculeMode:'Atom uses one nucleus. Diatomic uses two selected nuclei and an internuclear distance.',atomA:'Element for centre A. Its atomic number fills ZA.',atomB:'Element for centre B. Its atomic number fills ZB.',za:'Nuclear charge on centre A.',zb:'Nuclear charge on centre B. Use 0 for atoms.',r:'Internuclear distance in atomic units unless the input card says angstrom.',charge:'Total molecular charge used by the config card.',gridSpec:'X2DHF grid card values. Use N R for one segment, or Nnu Nmu R for manual two-dimensional segmented control.',orbpot:'Initial source of orbitals and potentials: hydrogen, hf, lda, ldasap, old, noexch, nodat, gauss, qrhf.',orbitals:'Config occupation cards after config charge. The final occupation row must include end.',lcao:'Hydrogenic LCAO initialization data for orbitals when orbpot hydrogen is used.',advancedCards:'Optional extra X2DHF cards inserted before stop, one per line.',scfMacro:'Maximum SCF macro iterations. You can set this up to 5000000; the runtime stops earlier when convergence is reached.',scfOrbital:'Orbital convergence control value.',scfPotential:'Potential convergence control value.',scfExtra:'Additional SCF control value.',scfMix:'SCF mixing/control value.',conv:'Optional convergence guard.',multipol:'Optional multipole boundary setting.',properties:'Request multipole moments after convergence.'};
const clean=value=>String(value||'').trim();
const first=(text,pattern,fallback='')=>(text.match(pattern)||[])[1]||fallback;
const symbolFromZ=z=>elements.find(item=>Number(item[1])===Math.round(Number(z)))?.[0]||'H';
const elementFromText=value=>{const text=clean(value).split(/\s|-/)[0];return elementMap[text]||elementMap[text.charAt(0).toUpperCase()+text.slice(1).toLowerCase()]||elementMap.H;};
const parseSample=input=>{const za=first(input,/^nuclei\s+(\S+)/im,defaults.za);const zb=(input.match(/^nuclei\s+\S+\s+(\S+)/im)||[])[1]||defaults.zb;const functional=first(input,/^dft\s+(.+)$/im,defaults.functional);return {title:first(input,/^title\s+(.+)$/im,defaults.title),theory:first(input,/^method\s+(\S+)/im,defaults.theory).toLowerCase(),functional:functionals.includes(functional)?functional:'custom',functionalCustom:functionals.includes(functional)?'':functional,moleculeMode:Number(zb)>0?'diatomic':'atom',atomA:symbolFromZ(za),atomB:Number(zb)>0?symbolFromZ(zb):'None',za,zb,r:(input.match(/^nuclei\s+\S+\s+\S+\s+(\S+)/im)||[])[1]||defaults.r,charge:first(input,/^config\s+(\S+)/im,defaults.charge),orbitals:(input.match(/^config.*?\n([\s\S]*?)\ngrid/im)||[])[1]?.trim()||defaults.orbitals,gridSpec:first(input,/^grid\s+(.+)$/im,defaults.gridSpec),orbpot:first(input,/^orbpot\s+(.+)$/im,defaults.orbpot),lcao:(input.match(/^lcao\s*\n([\s\S]*?)\nscf/im)||[])[1]?.trim()||defaults.lcao,scfMacro:first(input,/^scf\s+(\S+)/im,defaults.scfMacro),scfOrbital:(input.match(/^scf\s+\S+\s+(\S+)/im)||[])[1]||defaults.scfOrbital,scfPotential:(input.match(/^scf\s+\S+\s+\S+\s+(\S+)/im)||[])[1]||defaults.scfPotential,scfExtra:(input.match(/^scf\s+\S+\s+\S+\s+\S+\s+(\S+)/im)||[])[1]||defaults.scfExtra,scfMix:(input.match(/^scf\s+\S+\s+\S+\s+\S+\s+\S+\s+(\S+)/im)||[])[1]||defaults.scfMix,conv:first(input,/^conv\s+(.+)$/im,''),multipol:first(input,/^multipol\s+(.+)$/im,''),properties:/^mmoments$/im.test(input)}};
const Hint=({id})=><span className="mt-1 block text-xs leading-relaxed text-slate-500">{help[id]}</span>;
const HelpButton=({message})=><button type="button" onClick={()=>window.alert(message)} className="grid h-7 w-7 place-items-center rounded-full border border-cyan-300/25 bg-cyan-400/10 text-xs font-bold text-cyan-100 hover:bg-cyan-400/20" title="Show guidance">?</button>;
const TextInput=({id,label,form,update,placeholder=''})=><label className="text-xs text-slate-400">{label}<input name={id} value={form[id]} onChange={update} placeholder={placeholder} title={help[id]} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-slate-100 outline-none transition focus:border-cyan-400 focus:shadow-[0_0_0_3px_rgba(34,211,238,.12)]"/><Hint id={id}/></label>;
const ElementInput=({name,label,value,onChange,allowNone=false})=>{
 const [open,setOpen]=useState(false);
 const choices=elements.filter(item=>allowNone||item[0]!=='None');
 const visible=choices.filter(([symbol,,elementName])=>`${symbol} ${elementName}`.toLowerCase().includes(clean(value).toLowerCase())).slice(0,36);
 const setValue=symbol=>{onChange({target:{name,value:symbol}});setOpen(false);};
 return <label className="relative block text-xs text-slate-400">{label}<div className="mt-1 flex rounded-lg border border-slate-700 bg-slate-900 focus-within:border-cyan-400 focus-within:shadow-[0_0_0_3px_rgba(34,211,238,.12)]"><input name={name} value={value} onChange={e=>{onChange(e);setOpen(true);}} onFocus={()=>setOpen(true)} title={help[name]} placeholder={allowNone?'None or symbol':'Symbol'} className="min-w-0 flex-1 rounded-l-lg border-0 bg-transparent px-3 py-2 text-slate-100 outline-none"/><button type="button" onClick={()=>setOpen(state=>!state)} className="grid w-10 place-items-center rounded-r-lg border-l border-slate-700 bg-slate-950 text-cyan-200 hover:bg-cyan-400/10" aria-label={`${label} picker`}><span className={`h-0 w-0 border-x-[5px] border-t-[6px] border-x-transparent border-t-cyan-300 transition ${open?'rotate-180':''}`}/></button></div>{open&&<div className="absolute left-0 right-0 top-[64px] z-50 rounded-lg border border-cyan-300/20 bg-slate-950 p-2 shadow-2xl shadow-cyan-950/60"><div className="mb-2 flex items-center justify-between"><span className="text-[11px] font-semibold uppercase tracking-[.18em] text-cyan-300/80">Pick element</span><button type="button" onClick={()=>setOpen(false)} className="rounded border border-slate-700 px-2 py-0.5 text-[11px] text-slate-300 hover:bg-slate-800">Close</button></div><div className="max-h-48 overflow-auto pr-1"><div className="grid grid-cols-2 gap-1">{visible.map(([symbol,z,elementName])=><button key={symbol} type="button" onClick={()=>setValue(symbol)} className={`rounded border px-2 py-1 text-left text-[11px] transition ${value===symbol?'border-cyan-300 bg-cyan-400/20 text-cyan-50':'border-slate-800 bg-slate-900 text-slate-300 hover:border-cyan-300/40 hover:bg-cyan-400/10'}`}><span className="font-semibold text-cyan-100">{symbol}</span><span className="ml-1 text-slate-500">{z?z:'-'}</span><div className="truncate text-slate-400">{elementName}</div></button>)}</div></div></div>}<div className="mt-2 flex flex-wrap gap-1">{['H','He','C','N','O','F','S','Cl','Fe','U'].filter(symbol=>allowNone||symbol!=='None').map(symbol=><button key={symbol} type="button" onClick={()=>setValue(symbol)} className="rounded border border-cyan-300/15 bg-cyan-400/5 px-2 py-0.5 text-[11px] text-cyan-100 hover:bg-cyan-400/15">{symbol}</button>)}{allowNone&&<button type="button" onClick={()=>setValue('None')} className="rounded border border-slate-700 bg-slate-900 px-2 py-0.5 text-[11px] text-slate-300 hover:bg-slate-800">None</button>}</div><Hint id={name}/></label>;
};
const Prompt=({title,body})=><div className="rounded-lg border border-cyan-300/15 bg-cyan-400/5 p-3"><div className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300/80">{title}</div><div className="mt-1 text-xs leading-relaxed text-slate-400">{body}</div></div>;

const ComputationForm=({systems,onClose,onSubmitted,nativeReady=true})=>{
 const dispatch=useDispatch();
 const [submitting,setSubmitting]=useState(false);
 const [submitError,setSubmitError]=useState('');
 const [science,setScience]=useState(null);
 const [parsed,setParsed]=useState(null);
 const [form,setForm]=useState(defaults);
 useEffect(()=>{computationAPI.getScience().then(response=>setScience(response.data)).catch(()=>setScience(null));},[]);
 const generated=useMemo(()=>{
 const lines=[`title ${clean(form.title)||'X2DHF calculation'}`,`method ${form.theory}`];
  const functional=form.functional==='custom'?clean(form.functionalCustom):clean(form.functional);
  if(form.theory==='dft')lines.push(`dft ${functional||'xc_lda_x'}`);
  lines.push(`nuclei ${clean(form.za)} ${clean(form.zb)} ${clean(form.r)}`,'config '+clean(form.charge));
  clean(form.orbitals).split('\n').filter(Boolean).forEach(line=>lines.push(` ${line.trim()}`));
  lines.push(`grid ${clean(form.gridSpec)||'151 35.0'}`,`orbpot ${clean(form.orbpot)||'hf'}`);
  if(clean(form.lcao)){lines.push('lcao');clean(form.lcao).split('\n').filter(Boolean).forEach(line=>lines.push(` ${line.trim()}`));}
  lines.push(`scf ${clean(form.scfMacro)} ${clean(form.scfOrbital)} ${clean(form.scfPotential)} ${clean(form.scfExtra)} ${clean(form.scfMix)}`);
  if(clean(form.conv))lines.push(`conv ${clean(form.conv)}`);
  if(clean(form.multipol))lines.push(`multipol ${clean(form.multipol)}`);
  if(form.properties)lines.push('mmoments');
  clean(form.advancedCards).split('\n').filter(Boolean).forEach(line=>lines.push(line.trim()));
  lines.push('stop');
  return lines.join('\n');
 },[form]);
 useEffect(()=>{const timer=setTimeout(()=>{computationAPI.parseInput(generated).then(response=>setParsed(response.data)).catch(()=>setParsed(null));},250);return()=>clearTimeout(timer);},[generated]);
 const update=e=>{const {name,value,type,checked}=e.target;setForm(data=>({...data,[name]:type==='checkbox'?checked:value}));};
 const updateMolecule=e=>{const {name,value}=e.target;setForm(data=>{const next={...data,[name]:value};if(name==='moleculeMode'&&value==='atom')next.atomB='None';if(name==='atomA')next.atomA=elementFromText(value).symbol;if(name==='atomB')next.atomB=value.toLowerCase().startsWith('none')?'None':elementFromText(value).symbol;const a=elementMap[next.atomA]||elementMap.H;const b=next.moleculeMode==='diatomic'&&next.atomB!=='None'?elementMap[next.atomB]:elementMap.None;const formula=b.z?`${a.symbol}${b.symbol}`:a.symbol;return {...next,za:String(a.z.toFixed(1)),zb:String(b.z.toFixed(1)),title:`${formula} ${next.theory.toUpperCase()} Python X2DHF`,orbitals:Number(a.z)+Number(b.z)>2?data.orbitals:'1 sigma + end'};});};
 const loadMoleculePreset=([name,mode,aSymbol,bSymbol,r])=>setForm(data=>{const a=elementMap[aSymbol]||elementMap.H;const b=mode==='diatomic'?(elementMap[bSymbol]||elementMap.None):elementMap.None;return {...data,moleculeMode:mode,atomA:a.symbol,atomB:b.symbol,za:String(a.z.toFixed(1)),zb:String(b.z.toFixed(1)),r,title:`${name} ${data.theory.toUpperCase()} Python X2DHF`,description:`Preset molecular system: ${name}`};});
 const setIterations=value=>setForm(data=>({...data,scfMacro:String(value)}));
 const loadExample=input=>setForm(data=>({...data,...parseSample(input),description:`Loaded repository sample: ${first(input,/^title\s+(.+)$/im,'X2DHF')}`}));
 const submit=async e=>{e.preventDefault();setSubmitting(true);setSubmitError('');const chosenFunctional=form.functional==='custom'?form.functionalCustom:form.functional;const payload={title:form.title,description:form.description,theory:form.theory,functional:form.theory==='dft'?chosenFunctional:'',molecular_system:form.molecular_system?Number(form.molecular_system):null,spin_multiplicity:1,num_electrons:Math.max(1,Math.round(Number(form.za)+Number(form.zb)-Number(form.charge))),scf_iterations:Math.min(5000000,Math.max(1,Number(form.scfMacro)||100)),convergence_threshold:1e-8,parameters:[{key:'x2dhf_input',value:generated},{key:'form_input',value:JSON.stringify(form)},{key:'parsed_cards',value:JSON.stringify(parsed||{})}]};try{const job=await dispatch(submitComputation(payload)).unwrap();onSubmitted?.(job);onClose();}catch(error){setSubmitError(typeof error==='string'?error:JSON.stringify(error));}finally{setSubmitting(false);}};
 const cards=parsed?.cards||[];
 return <div className="animated-panel mb-6 rounded-lg border border-cyan-300/10 bg-slate-950/90 p-6 shadow-2xl shadow-slate-950/40">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-bold text-white">Scientific Input Builder</h2><p className="text-sm text-slate-400">Choose atoms, theory, functional, grid, and SCF limit. The Python runtime generates X2DHF-style output.</p></div><span className={`rounded-full border px-3 py-1 text-sm ${parsed?.is_valid?'border-emerald-400/30 bg-emerald-400/10 text-emerald-200':'border-rose-400/30 bg-rose-400/10 text-rose-200'}`}>{parsed?.is_valid?'Input valid':`Missing: ${(parsed?.missing||[]).join(', ')}`}</span></div>
  <form onSubmit={submit} className="mt-5 grid grid-cols-1 gap-5 xl:grid-cols-3">
   <div className="space-y-4 xl:col-span-2">
    <div className="grid grid-cols-1 gap-3 md:grid-cols-3"><Prompt title="Input deck" body="The form writes title, method, nuclei, config, grid, orbpot, lcao, scf and stop cards in X2DHF order."/><Prompt title="Manual control" body="Every scientific field remains editable after presets, including charge, grid segmentation, orbitals, and advanced cards."/><Prompt title="Runtime" body="SCF accepts up to 50 lakh macro iterations and shows an active runtime panel for long jobs."/></div>
    <div className="grid grid-cols-1 gap-4 md:grid-cols-2"><TextInput id="title" label="Calculation title" form={form} update={update}/><label className="text-xs text-slate-400">Theory<select name="theory" value={form.theory} onChange={update} title={help.theory} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-4 py-2 text-slate-100 outline-none transition focus:border-cyan-400"><option value="hf">Hartree-Fock</option><option value="dft">Python DFT</option><option value="hfs">HFS</option><option value="oed">OED</option><option value="ted">TED</option><option value="scmc">SCMC</option></select><Hint id="theory"/></label></div>
    {form.theory==='dft'&&<div className="grid grid-cols-1 gap-4 md:grid-cols-2"><label className="block text-xs text-slate-400">Libxc functional<select name="functional" value={form.functional} onChange={update} title={help.functional} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-4 py-2 text-slate-100 outline-none focus:border-cyan-400">{functionals.map(item=><option key={item} value={item}>{item}</option>)}</select><Hint id="functional"/></label>{form.functional==='custom'&&<TextInput id="functionalCustom" label="Custom Libxc labels" form={form} update={update} placeholder="xc_gga_x_b88 xc_gga_c_lyp"/>}</div>}
    <section className="rounded-lg border border-cyan-300/10 bg-slate-900/60 p-4"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="font-semibold text-white">Atom and Molecule Builder</h3><div className="flex items-center gap-2"><span className="rounded-full border border-cyan-300/20 px-3 py-1 text-xs text-cyan-100">118 searchable elements</span><HelpButton message={'Atom and molecule builder:\\n\\n1. Pick single atom or diatomic molecule.\\n2. Centre A fills ZA. Centre B fills ZB, or use None for atoms.\\n3. R is the internuclear distance in bohr unless your card says angstrom.\\n4. ZA/ZB stay editable for effective-charge experiments.'}/></div></div><div className="grid grid-cols-1 gap-4 lg:grid-cols-4"><label className="text-xs text-slate-400">System<select name="moleculeMode" value={form.moleculeMode} onChange={updateMolecule} title={help.moleculeMode} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-slate-100 outline-none focus:border-cyan-400"><option value="atom">Single atom</option><option value="diatomic">Diatomic molecule</option></select><Hint id="moleculeMode"/></label><ElementInput name="atomA" label="Centre A atom" value={form.atomA} onChange={updateMolecule}/><ElementInput name="atomB" label="Centre B atom" value={form.atomB} onChange={updateMolecule} allowNone/><TextInput id="r" label="Bond distance R" form={form} update={update}/></div><div className="mt-3 rounded border border-slate-800 bg-black/30 p-3 text-xs text-slate-300">Selected system: <span className="font-semibold text-cyan-100">{form.atomA}{form.moleculeMode==='diatomic'&&form.atomB!=='None'?form.atomB:''}</span>. Type symbols like H, O, Fe, U, or None for centre B. ZA/ZB are filled automatically but stay editable.</div></section>
    <section className="rounded-lg border border-slate-800 bg-slate-900/50 p-4"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="font-semibold text-white">Molecule Presets</h3><HelpButton message={'Molecule presets load common atom/diatomic systems into ZA, ZB, and R. You can still override every generated value manually after loading.'}/></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{moleculePresets.map(preset=><button key={preset[0]} type="button" onClick={()=>loadMoleculePreset(preset)} className="rounded-lg border border-cyan-300/15 bg-cyan-400/5 px-3 py-2 text-left text-xs text-cyan-100 transition hover:border-cyan-300/40 hover:bg-cyan-400/15"><div className="font-semibold">{preset[0]}</div><div className="text-slate-500">{preset[1]} | R {preset[4]}</div></button>)}</div></section>
    <label className="block text-xs text-slate-400">Description<textarea name="description" value={form.description} onChange={update} title={help.description} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-4 py-2 text-slate-100 outline-none focus:border-cyan-400"/><Hint id="description"/></label>
    <div className="grid grid-cols-2 gap-4 md:grid-cols-4">{[['za','ZA'],['zb','ZB'],['r','R'],['charge','Config charge']].map(([id,label])=><TextInput key={id} id={id} label={label} form={form} update={update}/>)}</div>
    <div className="rounded-lg border border-slate-800 bg-slate-900/50 p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-semibold text-white">Grid and Potential Cards</h3><HelpButton message={'Grid card prompt:\\n\\nUse `grid N R` for a compact one-section grid, for example `grid 151 35.0`.\\nUse `grid Nnu Nmu R` for two-dimensional manual control, for example `grid 251 251 80.0`.\\nLarger N values cost more CPU and memory.'}/></div><p className="text-xs text-slate-500">Same style as X2DHF: compact grid cards for one or multiple finite-difference sections.</p></div><div className="flex flex-wrap gap-2">{['151 35.0','191 65.0','251 251 80.0','401 401 120.0'].map(item=><button key={item} type="button" onClick={()=>setForm(data=>({...data,gridSpec:item}))} className="rounded-full border border-cyan-300/20 bg-cyan-400/10 px-3 py-1 text-xs text-cyan-100 hover:bg-cyan-400/20">{item}</button>)}</div></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><TextInput id="gridSpec" label="Grid card values" form={form} update={update} placeholder="151 35.0 or 151 151 35.0"/><TextInput id="orbpot" label="Orbital potential" form={form} update={update}/></div></div>
    <label className="block text-xs text-slate-400">Orbital occupations<textarea name="orbitals" value={form.orbitals} onChange={update} title={help.orbitals} className="mt-1 h-24 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 font-mono text-sm text-slate-100 outline-none focus:border-cyan-400"/><Hint id="orbitals"/></label>
    <label className="block text-xs text-slate-400">LCAO rows<textarea name="lcao" value={form.lcao} onChange={update} title={help.lcao} className="mt-1 h-24 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 font-mono text-sm text-slate-100 outline-none focus:border-cyan-400"/><Hint id="lcao"/></label>
    <label className="block text-xs text-slate-400">Advanced X2DHF cards<textarea name="advancedCards" value={form.advancedCards} onChange={update} title={help.advancedCards} placeholder="Optional cards, one per line" className="mt-1 h-20 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 font-mono text-sm text-slate-100 outline-none focus:border-cyan-400"/><Hint id="advancedCards"/></label>
    <div className="grid grid-cols-2 gap-4 md:grid-cols-5">{[['scfMacro','SCF'],['scfOrbital','Orb tol'],['scfPotential','Pot tol'],['scfExtra','Extra'],['scfMix','Mix']].map(([id,label])=><TextInput key={id} id={id} label={label} form={form} update={update}/>)}</div>
    <div className="flex flex-wrap gap-2">{iterationPresets.map(value=><button key={value} type="button" onClick={()=>setIterations(value)} className="rounded-full border border-cyan-300/25 bg-cyan-400/10 px-3 py-1 text-xs font-semibold text-cyan-100 transition hover:bg-cyan-400/20">{value.toLocaleString('en-IN')} SCF</button>)}</div>
    <div className="grid grid-cols-1 gap-4 md:grid-cols-3"><TextInput id="conv" label="Conv" form={form} update={update} placeholder="optional"/><TextInput id="multipol" label="Multipol" form={form} update={update} placeholder="optional"/><label className="flex flex-col justify-end gap-2 pb-2 text-sm text-slate-300"><span><input type="checkbox" name="properties" checked={form.properties} onChange={update}/> Moments</span><Hint id="properties"/></label></div>
    {submitError&&<div className="rounded-lg border border-rose-400/30 bg-rose-950/50 p-3 text-sm text-rose-100">{submitError}</div>}
   </div>
   <aside className="space-y-4">
    <section className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><h3 className="mb-2 font-semibold text-white">Samples</h3><div className="max-h-56 space-y-2 overflow-auto">{[...Object.entries(science?.examples||{}).map(([name,input])=>({name,input})),...(science?.test_sets||[]).slice(0,40)].map(item=><button type="button" key={item.name} onClick={()=>loadExample(item.input)} className="block w-full rounded border border-slate-700 px-3 py-2 text-left text-sm text-slate-200 transition hover:border-cyan-400 hover:bg-cyan-400/10">{item.name}</button>)}</div></section>
    <section className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><h3 className="mb-2 font-semibold text-white">Guidance</h3><div className="space-y-2 text-xs text-slate-400"><p>Choose any element, then run HF, DFT, HFS, OED, TED, or SCMC.</p><p>Set Centre B to None for atoms, or choose another element for diatomics.</p><p>Manual ZA/ZB edits remain available for effective-charge experiments.</p><p>Use SCF presets up to 50 lakh for long convergence studies.</p></div></section>
    <section className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><h3 className="mb-2 font-semibold text-white">Generated Python Runtime Input</h3><pre className="max-h-64 overflow-auto rounded bg-black p-3 text-xs text-emerald-100">{generated}</pre></section>
    <section className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><h3 className="mb-2 font-semibold text-white">Parsed Meanings</h3><div className="max-h-64 space-y-2 overflow-auto">{cards.map(card=><div key={`${card.line}-${card.raw}`} className="rounded border border-slate-800 p-2"><div className="font-mono text-xs text-cyan-100">{card.raw}</div><div className="text-xs text-slate-400">{card.meaning}</div></div>)}</div></section>
    <div className="flex gap-2"><button type="submit" disabled={submitting||!parsed?.is_valid||!nativeReady} className="rounded-lg bg-cyan-400 px-6 py-2 font-semibold text-slate-950 transition hover:bg-cyan-300 disabled:bg-slate-700 disabled:text-slate-400">{submitting?'Submitting...':'Run Computation'}</button><button type="button" onClick={onClose} className="rounded-lg bg-slate-800 px-6 py-2 text-slate-200 transition hover:bg-slate-700">Close</button></div>
   </aside>
  </form>
 </div>;
};

export default ComputationForm;
