import os
from pathlib import Path
from datetime import timedelta
BASE_DIR=Path(__file__).resolve().parent.parent
SECRET_KEY=os.environ.get('DJANGO_SECRET_KEY','django-insecure-x2dhf-saas-dev-key')
DEBUG=os.environ.get('DEBUG','False')=='True'
ALLOWED_HOSTS=os.environ.get('ALLOWED_HOSTS','localhost,127.0.0.1').split(',')
INSTALLED_APPS=[
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'djoser',
    'django_filters',
    'users',
    'computations',
    'results',
    'billing',
    'core',
    'admin_api',
]
MIDDLEWARE=[
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF='x2dhf_project.urls'
TEMPLATES=[{
    'BACKEND':'django.template.backends.django.DjangoTemplates',
    'DIRS':[os.path.join(BASE_DIR,'templates')],
    'APP_DIRS':True,
    'OPTIONS':{'context_processors':['django.template.context_processors.debug','django.template.context_processors.request','django.contrib.auth.context_processors.auth','django.contrib.messages.context_processors.messages']},
}]
WSGI_APPLICATION='x2dhf_project.wsgi.application'
DATABASES={
    'default':{
        'ENGINE':'django.db.backends.postgresql',
        'NAME':os.environ.get('DB_NAME','x2dhf'),
        'USER':os.environ.get('DB_USER','postgres'),
        'PASSWORD':os.environ.get('DB_PASSWORD',''),
        'HOST':os.environ.get('DB_HOST','localhost'),
        'PORT':os.environ.get('DB_PORT','5432'),
    }
}
AUTH_PASSWORD_VALIDATORS=[
    {'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator'},
]
LANGUAGE_CODE='en-us'
TIME_ZONE='UTC'
USE_I18N=True
USE_TZ=True
STATIC_URL='/static/'
STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS=os.environ.get('CORS_ORIGINS','http://localhost:3000,http://localhost:8000').split(',')
REST_FRAMEWORK={
    'DEFAULT_AUTHENTICATION_CLASSES':['rest_framework_simplejwt.authentication.JWTAuthentication',],
    'DEFAULT_PERMISSION_CLASSES':['rest_framework.permissions.IsAuthenticated',],
    'DEFAULT_FILTER_BACKENDS':['django_filters.rest_framework.DjangoFilterBackend','rest_framework.filters.SearchFilter','rest_framework.filters.OrderingFilter'],
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':20,
}
SIMPLE_JWT={
    'ACCESS_TOKEN_LIFETIME':timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME':timedelta(days=7),
    'ALGORITHM':'HS256',
    'SIGNING_KEY':SECRET_KEY,
}
STRIPE_SECRET_KEY=os.environ.get('STRIPE_SECRET_KEY','')
STRIPE_PUBLIC_KEY=os.environ.get('STRIPE_PUBLIC_KEY','')
EMAIL_BACKEND=os.environ.get('EMAIL_BACKEND','django.core.mail.backends.console.EmailBackend')
EMAIL_HOST=os.environ.get('EMAIL_HOST','smtp.gmail.com')
EMAIL_PORT=int(os.environ.get('EMAIL_PORT',587))
EMAIL_USE_TLS=os.environ.get('EMAIL_USE_TLS','True')=='True'
EMAIL_HOST_USER=os.environ.get('EMAIL_HOST_USER','')
EMAIL_HOST_PASSWORD=os.environ.get('EMAIL_HOST_PASSWORD','')
AUTO_START_COMPUTATIONS=os.environ.get('AUTO_START_COMPUTATIONS','False')=='True'
X2DHF_PATH=os.environ.get('X2DHF_PATH','/usr/local/bin/x2dhf')
X2DHF_DFT_PATH=os.environ.get('X2DHF_DFT_PATH','/usr/local/bin/x2dhf_dft')
QE_PATH=os.environ.get('QE_PATH','/usr/local/bin/pw.x')
LIBXC_PATH=os.environ.get('LIBXC_PATH','/usr/local/lib')
LOGGING={
    'version':1,
    'disable_existing_loggers':False,
    'handlers':{'console':{'class':'logging.StreamHandler'}},
    'root':{'handlers':['console'],'level':'INFO'},
}
